# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-27 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfumigadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Mision',
            },
        ),
        migrations.CreateModel(
            name='Somos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Somos',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Vision',
            },
        ),
    ]
