# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-05 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfumigadora', '0005_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('foto', models.ImageField(upload_to='Fotos')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfumigadora.Area')),
            ],
        ),
    ]
